dist: trusty
os: linux
language: java
install: true
jdk: openjdk8
script:
  - 'if [ "$TRAVIS_PULL_REQUEST" = "false" ] && [ "$TRAVIS_BRANCH" = "master" ]; then gradle publish; else gradle jbake; fi'

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

env:
  global:
  - secure: "r8CPz90yexdhJpIrVT80dlW979DJcFYXwL1A7qCJruc2DTaA4R4VmzEfC7SfbuUEofI6KUPvPzW+NOmFS6BGrXJwN5VfH9ffsTCBW5Dzzk9XR0zY5WPJythFj8EUXcOMe0ibApdoI+gBpT26sjWF1Q1IGk9XwOxlYFFEeyI8kP+thb6qv2w4hDMUPszOno00M2H46FEVTxbMIas4Lax2ymL8TZdVg8XMU4Gm1PmJDBRJsCQ33VcAhKr4xOVbsgPFbn9mMt5eKuwdyoJ2YuS2E6+jDCCJ8P05gBKpd34IjR5mK4DB2U0p4BpSKl2Fp/kVlMVJCWMUWo2GmvX2C1D74FVhDl6qJ/iq9fTY0i6vSNGSdH0e1yW4+AJ8yk8tFdtyIEsBNZyvbvQAKI5ugB41Ya3cEJWQTJI9mhUQ428y+jBBYWxgS1XOvuUlwnigmD70FTAx0egou/RLbtwaSYxPnTCLC5VuIVNxfKhXqL5ViDD7LaHRVwJ6ezvSQPBD4Ps3Z6jYYAGEj8RhZpR31Ki7wxcKcq2ykp794jliBRFVH4AKR+M+y4sBRn60otNkrt7bP7222kfbdZSfZPtmcRSQy1A35INUn1hv8uGavFojNVXdyZzm6nz3qvztMTUpBOGkVwczHHVWdKCiRaCPVuVV9Td8uPMbU2g2gh4uQfS1Lqw="
