title=Newsletter August 2018
date=2018-08-15
type=post
tags=blog, asciidoc
status=published
~~~~~~
= Newsletter August 2018
2018-08-15

Hello Chicago!

Welcome to the August 2018 CJUG Newsletter. We’ve got a lot going on, so let’s dig right in!

We are very pleased to announce that link:https://twitter.com/jtigp[Janine Patterson], our former Community Director has been elected CJUG President, taking over for link:https://twitter.com/fguime[Freddy Guime] whose job has moved him to Seattle. Additionally, link:https://twitter.com/toddginsberg[Todd Ginsberg] has been named Community Leader, taking over for Janine.

We all wish Freddy the best in his new place, and hope he’ll make as much of a positive impact on Seattle’s Java scene as he’s done in Chicago. 

=== Upcoming Events
August is half over but we still have more great things planned.

*Ask the Spring Team Anything* +
Wednesday August 29th at Pivotal Labs

This event is going to be very special, as we have several Spring project leads coming in to link:https://www.meetup.com/ChicagoJUG/events/252975162/[talk with us at Pivotal Labs]. Rather than pick one person to give a talk, we figured we would have a panel discussion about anything Spring related, and let you, the community, decide where the conversation goes.

We will have a discussion with:

* link:https://twitter.com/starbuxman[Josh Long] - Spring Developer Advocate 
* link:https://twitter.com/littleidea[Andrew Clay Schafer] - Pivotal Senior Director of Technology
* link:https://twitter.com/z_oleg[Oleg Zhurakousky] - Lead of Spring Cloud Stream and Spring Cloud Function
* link:https://twitter.com/jon_k_schneider[Jon Schneider] - Spring Metrics and Spring Cloud
* link:https://twitter.com/michaelminella[Michael Minella] - Spring Batch Lead and CJUG Board Member
* link:https://twitter.com/spencerbgibb[Spencer Gibb] - Co-founder and Lead of Spring Cloud
* link:https://twitter.com/mariogray[Mario Gray] - Pivotal Principal Technologist

If you use Spring at all, this will be a great opportunity to come find out where your favorite Spring projects are going, and have your questions answered. So put your thinking caps on, come up with some questions you’ve been dying to know the answer to, and RSVP before we fill up. Personally, I can’t wait to find out why Michael Minella flipped that tortoise over in the desert.

link:https://www.meetup.com/ChicagoJUG/events/252975162/[RSVP for Ask the Spring Team Anything at Meetup.com].


*Office Hours* +
Monday. August 20th at Rocketmiles

We will be holding August’s office hours at Rocketmiles. Got a project you need help with? New to Java and want some concepts explained, or help sorting out all of your options? Want to just come hang out and code? Come to CJUG Office Hours. 

Our optional topic this month is going to be Interviewing Skills. We’ll have several people on hand who regularly interview developers to help you approach problems you might encounter, give you tips on what to do in an interview, and come up with mock questions to go over. If you’re actively looking to change jobs, or plan on looking soon, come let us help build up your confidence.

link:https://www.meetup.com/ChicagoJUG/events/253609979/[RSVP for Office Hours at Meetup.com].

=== Spring One Tour

Pivotal is bringing the link:https://springonetour.io/2018/chicago[Spring One Tour through Chicago] on August 28 and 29. For $150 you get two full days of talks (single track, so you don’t miss anything!), breakfasts, lunches, and a networking social. There will even be an open space in the afternoon on the first day so you can suggest and participate in whatever kind of talks you want! There are some great speakers coming to this event, and you’re guaranteed to learn a lot. 

So get that sales pitch ready and convince your boss to dip into the training budget, this is a bargain at $150.

=== Java Off Heap

Several members of the CJUG board have a podcast focused on Java news called Java Off Heap, and you can find it in link:https://itunes.apple.com/us/podcast/javapubhouse-off-heaps-podcast/id985064111?mt=2[iTunes] or link:http://www.javaoffheap.com/[javaoffheap.com].

Did you know there is a string concatenation bug in Java 9 and 10? Or that there are plans to remove Serializable? Oracle recently open sourced Java Mission Control, what does that mean for the community? What happens to Jakarta EE (the new group in charge of what was Java EE) if Oracle doesn’t transfer the EE specifications to them? Find out by downloading and listening to Episode 35.

=== Chirp!
Be sure to follow link:https://twitter.com/cjug[CJUG on twitter @CJUG] for up to date information on what we’re up to. We announce all of our meetups and tweet out interesting news from our industry. As always, be part of the community by tweeting us your suggestions or requests for speakers or topics.

=== Thank You!
We couldn’t do what we do for the Java community in Chicago without the help of our fantastic Gold Level Sponsors. They fund our operations, donate equipment, and generously donate their time and space for us to meet. Please consider them if you are looking to switch jobs soon.

*Expedia Group*

Expedia has generously donated 30 laptops for CJUG which were recently used at our first CJUG4Kids event. We appreciate Expedia’s generous donation to the Chicago Java User Group and we look forward to using the laptops for more events especially CJUG4Kids.  Additionally, Expedia has been very generous with their space for a number of CJUG events.  We are very excited to have them on as Gold Sponsors!

*Peak 6*

Peak6 has provided CJUG with a generous donation that will help fund additional laptop chargers, speaker gifts, and community events (such as the Polyglot Party!). Peak6 has been tremendous community partners over the years supplying space, speakers, and frosty beverages. We are very thankful for there support and look forward to partnering with them as Gold Sponsors.

=== Contact Us

Interested in having your company host a future CJUG meetup? Want to help but don’t know where to start?  Have an idea for a topic that you want to see more of, or want to present yourself? How about some feedback on CJUG to make it better? 

Mail us at board@cjug.org and we will hook you up with the right person.

=== Finally...

Whew! I told you we had a lot going on in August! See you in September with more news.

Thanks for reading,

*Todd Ginsberg* +
*CJUG Community Leader* +
todd.ginsberg@cjug.org
