title=Newsletter April 2018
date=2018-04-02
type=post
tags=blog, asciidoc
status=published
~~~~~~
= Newsletter April 2018
2018-04-02

Ready, Set, Go!

Hello!  I’m excited to bring you my first newsletter as the CJUG Community Leader!  We’ve got some amazing things planned for this year, so keep your eyes and your mailbox open.  :-)

=== New Website
We’ve officially launched our new website @ link:https://cjug.org[https://cjug.org].  Check out previous newsletters, upcoming meetup events, and new announcements.


=== 2018 Officers
In case you missed it, our 2018 board has been chosen.

President - Freddy ‘Resident Cat Herder’ Guime +
Chairman of the Board - Jonathan ‘No Rubbish’ Ross +
Chief Financial Officer - Todd ‘Just the JVM Please’ Ginsberg +
Director of Meetings - Mary ‘Requirements - ¯\\_(ツ)_/¯’ Grygleski +
Director of Sponsorship - Bob ‘Independently Awesome’ Paulin +
Community Leader - Janine ‘It Works on My Box’ Patterson


=== Summer of Fun!
We have some great speakers lined up for the summer.  Check out link:https://meet.meetup.com/wf/click?upn=pEEcc35imY7Cq0tG1vyTt3miACH3kxpXb8TgLtvZl9cNDVLrtlGHZ5fUx-2FeBx5dVwjip-2BjZ4VPJA8dHaQmQ1bA-3D-3D_OGSh7qcBXBPPzK5pKXbBZVbbZPwgY0-2Bo1ELc-2Bxqa-2BlvPCm2fp9aO-2FLcGqOGoqjJLrsgaf0OOQw-2F6xemGQ4hjiBT0AQItCz169LNcgt6r3mq2lLhdXb7iDeJ-2FKiwm9zJ1nQ6NqJX8PJRweCh-2F3-2F5mCbp3bDVUxjdqwfs1uuyUNfYkMxf61KNhwnrZTyxKAFZYUmWXSmdnHIfVACDjW1KAfw1AN847zalS1eBgPBBbCm0-3D[Bruno Souza Presents: 3 steps for an amazing Java career] on April 9th.  Bruno is stopping in Chicago as part of his JUG Tour around the US.  He’ll be giving some sage and fun advice on how to build your awesome career!

The next monthly link:https://meet.meetup.com/wf/click?upn=pEEcc35imY7Cq0tG1vyTt3miACH3kxpXb8TgLtvZl9cNDVLrtlGHZ5fUx-2FeBx5dVAmjDamhgSZ5hEykE9SzRGQ-3D-3D_OGSh7qcBXBPPzK5pKXbBZVbbZPwgY0-2Bo1ELc-2Bxqa-2BlvPCm2fp9aO-2FLcGqOGoqjJLrsgaf0OOQw-2F6xemGQ4hjiOHVhIKKXgLmliDT0b6s5Z1MgeqUq4Rz3NByz-2F-2For-2BMlisMRV76CRyMH2-2BqmtRzhia37kOsc55b1S-2FJQOf0QhK4e27wyntJhlQaapLwlgkXo9iXU-2FJuE5Ejg8a3Tci5LkmV-2FXoKZ9HxqzWjceyPFuC8-3D[Office Hours] is scheduled for April 17th.  If you’d like to request a topic for the next office hours, or want to volunteer to be an office hours aide, contact mailto:todd.ginsberg@cjug.org[Todd] or mailto:janine.patterson@cjug.org[Janine].

Mark your calendar for April 19th.  Thomas Nield will present Data Science with Kotlin.  Kotlin is hitting the prime time as a JVM language for Big Data, and Thomas will show us how.

link:https://meet.meetup.com/wf/click?upn=pEEcc35imY7Cq0tG1vyTt46osmEo83Q98LZcdaoX80U-3D_OGSh7qcBXBPPzK5pKXbBZVbbZPwgY0-2Bo1ELc-2Bxqa-2BlvPCm2fp9aO-2FLcGqOGoqjJLrsgaf0OOQw-2F6xemGQ4hjiDMCCrZ8Ornar9og6DPc7Vh03mSjqSySta7D4m8-2FmWNHLeCu-2F96BEOcNNHEQLrqrvB12yNwK9FbWjPLoC72fAIR5IgwxSvrnCzQ-2FMkFnIutNRJ5Exq1KqhlF9NBNWgIKQI2U88DHk7r-2FFlzfjaeIEc8-3D[GOTO Chicago] is coming up soon.  Talks are on April 25th and 26th.  Workshops on April 24th and 27th. Registration is still open.

Keep an eye on the calendar.  CJUG has two speakers scheduled for every month this summer.  Announcements will be made in a timely fashion before each speaker’s talk.



=== Calling All Speakers
Interested in getting involved in the speaker circuit?  Want to talk at a CJUG event? We’re mixing it up this year by adding lightning talks this June.  Talks should aim to be around 5-10 minutes, on any technical topic you’d like. This will be a great opportunity for new and experienced speakers to flex their skills in front of a very chill and supportive crowd.  Some of our members have used events like this in the past to get involved, and have subsequently presented at DevNexus and Oracle Code this year. We’re giving you an extra heads up so you can consider your topic.



=== Good Things Come to Those Who Wait…
If you’ve been to a CJUG meetup lately, you’ve seen that we are looking for more volunteers.  We’ve got some exciting things in the pipeline that we’re getting ready to announce. More opportunities to work with our community locally, or maybe travel? Hmmmm…. Keep an eye on your email...


Gotta run, just discovered a new cache of cat gifs on the internet.  Until next time!

*~ Janine Patterson ~* +
*Community Leader* +
janine.patterson@cjug.org