title=Newsletter May 2018
date=2018-05-03
type=post
tags=blog, asciidoc
status=published
~~~~~~
= Newsletter May 2018
2018-05-03

Hello again!  May is already upon us and the weather has finally decided to catch up!  The snow was fun while it lasted, but these warm summer days couldn’t come soon enough.  CJUG is ready to hit the ground running this summer with some very exciting new events.



=== Kids Are The Future!
June 9th - CJUG is proud to announce our first CJUG4Kids event!  Want to get your kids excited about programming? We have a workshop that combines link:https://www.eventbrite.com/e/cjug4kids-lets-mod-minecraft-tickets-45542955205[Java and Minecraft] with some cool modding code.  (Snowballs that contain arrows WAAAAA???)  We’re planning on holding a few more workshops this summer so keep watching.  If you’re interested in getting involved, send an email to cjug4kids@cjug.org.

June 2nd - Partner Event - We are also excited to share with you another kid focused event with Hak4Kidz.  link:http://www.hak4kidz.com/[Hak4Kidz] is an event of ethical hackers and Information Security professionals dedicated to bring the educational and communal benefits of white hat hacking conferences to children and young adults. We accomplish this mission by putting our collective expertise and passion on display for the attendees to interact with us at their will. A combination of activity stations and detailed workshops will enable the attendees to expand and enlighten their technical interests. For innovation to perpetuate, it’s imperative that today’s young users are exposed to the bigger picture of how we got here and to help realize their potential.  Check out registration link:http://www.hak4kidz.com/eventchi.html[Here].



=== Upcoming Events
May 10th - We’re deeply committed to supporting and enhancing the OSS community.  CJUG’s own Bob and Josh will lead a discussion on how you can link:https://www.meetup.com/ChicagoJUG/events/249969567/[participate and give back to the OSS community].  From the Dark Web to the Panama Papers, you’d be surprised at how OSS contribution has impacted some of the most compelling recent scandals.  (This will be a virtual event)

May 16th - The next monthly link:https://www.meetup.com/ChicagoJUG/events/249371100/[Office Hours] is scheduled with a group project on Logging, led by Lamar Smith.  If you’d like to request a topic for the next office hours, or want to volunteer to be an office hours aide, contact mailto:todd.ginsberg@cjug.org[Todd] or mailto:janine.patterson@cjug.org[Janine].

May 21st - David Blevins will be presenting link:https://www.meetup.com/ChicagoJUG/events/249969823/[Deconstructing and Evolving REST Security].  Security for REST endpoints… you mean I’m not supposed to throw all of my apis on the open web and expose everything?  Ugh...



=== Lightning Talks
Time to get involved!  As mentioned in the last newsletters, Lightning Talks are coming up soon.  (Targeting early June) We’re looking for you to submit a 5-10 minute talk on the topic of your choosing.  This is a great chance to flex those speaking skills in front of our very supportive crowd. If you want to present email us at present@cjug.org.  If you’re not sure where to get started or have any questions feel free to email us at that address as well.



=== A Special Thanks
We’d like to make a special shoutout to our sponsor link:https://www.expedia.com/[Expedia] for their amazing donation of laptops that will help with our future workshops.  We cannot do what we do without our awesome sponsors. The donation of these laptops will allow us to do much more with our community and kids outreach programs.  Thanks so much!



*~ Janine Patterson ~* +
*Community Leader* +
janine.patterson@cjug.org

