title=Newsletter October 2018
date=2019-10-09
type=post
tags=blog, asciidoc
status=published
~~~~~~
= Newsletter October 2018
2018-10-09

Hello Chicago!


October is here and as usual we’ve been busy at CJUG World Headquarters planning exciting things for the Java community in Chicago. Now that Janine is CJUG is President, this probably a good time to let her know that according to our bylaws, she has to dress up as Duke for the meetup closest to Halloween. 

== Upcoming Events

*Venkat Subramaniam* +
Thursday, November 1

If you’ve never seen Venkat give a talk, you are in for a treat. We are very fortunate to have one of Java’s most popular and sought after speakers come back to preset to CJUG! Venkat presents on a wide variety of subjects and has offered us a choice. We thought it would be great to have YOU, the community, vote on what you want to see!


When you RSVP, take the survey and pick the topic that appeals to you the most:


* Benefiting from Java 9 Improvements
* Type Inference: Friend or Foe?
* Completable Future: The Promises of Java
* Design Patterns in the Light of Lambda Expressions
* Java Functional Programming Idioms
*Kotlin for Java Programmers

Even if your topic doesn’t end up being selected, it will still be a great presentation. RSVP before this fills up.


link:https://www.meetup.com/ChicagoJUG/events/255357346/[RSVP and Vote for Venkat’s Topic NOW!]



*OSS@CJUG* +
Thursday, October 11 at Noon (Online!)

Join Josh Juneau and Bob Paulin where they will go over the general contribution process that many open source projects have. What is a PR? How does branching work? Interacting with an established project. In addition, Bob will cover the Apache Incubation process, and Josh will cover Apache Krazo (MVC). 


link:https://www.meetup.com/ChicagoJUG/events/255381937/[RSVP for OSS@CJUG now!]



*Office Hours* +
Monday, October 22 at IBM @5:30pm

Got a project you need help with? New to Java and want some concepts explained, or help sorting out all of your options? Want to just come hang out and code? Come to CJUG Office Hours. 


Our optional topic this month is going to be Design Patterns, led by Nick. He will go over some common patterns you are likely to run into, what problems they are good at solving, and how to implement them in Java.


Note this one is starting a bit earlier than usual at 5:30.


link:https://www.meetup.com/ChicagoJUG/events/255369776/[RSVP for Office Hours now!]


== Lightning Talks Are Coming 

CJUG will be hosting Lightning Talks again in December, so put your thinking caps on and come up with a topic. You don’t have to have any experience with presenting, or professionally created slides, or even do live coding. Get up in front of our friendly CJUG audience and teach us about something you care about, have worked on, or are curious about. You just have to prepare a 5-10 minute talk on anything relating to Java or the JVM and tell us all about it. 


This is a great way to begin advancing your career. The ability to stand up in front of a group and teach makes you more attractive to future employers. It’s also the perfect opportunity to see if you enjoy speaking. Several CJUG members who got their start at Lightning Talks regularly present at conferences all around the country. 


We’re a friendly audience. We want you to succeed. You can do this.


== Java Off Heap

Several members of the CJUG board have a podcast focused on Java news called Java Off Heap, and you can find it in link:https://itunes.apple.com/us/podcast/javapubhouse-off-heaps-podcast/id985064111?mt=2[iTunes] or link:http://www.javaoffheap.com/[javaoffheap.com].

link:http://www.javaoffheap.com/2018/10/episode-37-jdk-11-is-out-java-licensing.html[Episode 37]: Extra Extra! If you work in Java you gotta take a break from all other news, and listen to this episode! Java is changing its pricing model, and with that comes a lot of new consequences. You can still get it for free, but you gotta know what you're getting into (Move to OpenJDK!). In another news, Redis is changing is BSD licensing (while usually free, now comes with a ton a caveats for cloud hosts). Lastly, Linus Torvalds (the only one who's a bigger curmudgeon than Michael Minella) has decided to apologize to those that had to endure his rants! Our industry is changing, and is moving forward!   

== Great Lakes Software Symposium CJUG Discount

Don’t Delay! Register today for the 2018 Great Lakes Software Symposium returning November 2nd - 4th!


The No Fluff Just Stuff Java Symposium Tour Series, long considered the definitive conference series for software developers & architects, returns to Chicago this fall! Witness first hand the best a conference has to offer: exceptional speakers, content rich 90 minute technical sessions, right sized event model (capped at 250 attendees) all experienced in a vendor free environment.  At a No Fluff Just Stuff event, the focus is entirely on the attendee experience and nothing else!


50+ new sessions for 2018 to choose from!


Event Name: 2018 Great Lakes Software Symposium +
Dates: Nov 2-4th +
Location: Itasca, IL +
Venue: Westin Chicago Northwest +
URL: https://nofluffjuststuff.com/conference/chicago/2018/11/home


Make sure and use the special CJUG discount of $50 by using the promo code nfjsusergroup50 when registering. If you are registering with a group, the highest discount will apply - group or CJUG discount.


Registration Fees

Early Bird Individual: $1,025/person through October 15.

Excellent Group Discounts Available - bring your entire development team to the show:


* 5-9 Attendees: $925/person
* 10-14 Attendees: $900/person
* 15-24 Attendees: $875/person
*25-over Attendees: $850/person


Why attend?

* Excellent Speakers: Authors and Project Leaders
* Insightful 90 minute Sessions
* Network with your local developer community
* No vendor promos
* Locally Based Event
* Great Venue
* Limited Attendance
* Meaningful Keynote
* Excellent Giveaways



What's Included

* Three Day All Access Pass
* Dinner & PM Breaks on Friday & Breakfast/Lunch & Breaks on Saturday/Sunday
* NFJS Laptop Bag & T-shirt
* Online Audio Recording of Available Sessions
* Subscription to NFJS, the Magazine - 2018 


Go to  https://nofluffjuststuff.com/conference/chicago/2018/11/home to see additional information and registration details for the 2018 Great Lakes Software Symposium.


=== Chirp!
Be sure to follow link:https://twitter.com/cjug[CJUG on twitter @CJUG] for up to date information on what we’re up to. We announce all of our meetups and tweet out interesting news from our industry. As always, be part of the community by tweeting us your suggestions or requests for speakers or topics.

=== Thank You!
We couldn’t do what we do for the Java community in Chicago without the help of our fantastic Gold Level Sponsors. They fund our operations, donate equipment, and generously donate their time and space for us to meet. Please consider them if you are looking to switch jobs soon.

*Expedia Group*

Expedia has generously donated 30 laptops for CJUG which were recently used at our first CJUG4Kids event. We appreciate Expedia’s generous donation to the Chicago Java User Group and we look forward to using the laptops for more events especially CJUG4Kids.  Additionally, Expedia has been very generous with their space for a number of CJUG events.  We are very excited to have them on as Gold Sponsors!

*PEAK6*

PEAK6 has provided CJUG with a generous donation that will help fund additional laptop chargers, speaker gifts, and community events (such as the Polyglot Party!). PEAK6 has been tremendous community partners over the years supplying space, speakers, and frosty beverages. We are very thankful for there support and look forward to partnering with them as Gold Sponsors.
Contact Us

Interested in having your company host a future CJUG meetup? Want to help but don’t know where to start?  Have an idea for a topic that you want to see more of, or want to present yourself? How about some feedback on CJUG to make it better? 

Mail us at link:mailto:board@cjug.org[board@cjug.org] and we will hook you up with the right person.

=== Finally...

As always, thanks for reading and letting us know what you think. We hope to see a lot of your at our upcoming meetings! If you dress up for Halloween in an especially technical costume, let us know!

Thanks for reading,

*Todd Ginsberg* +
*CJUG Community Leader* +
todd.ginsberg@cjug.org


