title=Newsletter September 2018
date=2018-08-15
type=post
tags=blog, asciidoc
status=published
~~~~~~
= Newsletter September 2018
2018-09-12


Hello Chicago!

Can you believe that September is here already? That means you only have a few more weeks to wring every last bit of fun out of the nice warm weather before winter sets in. We’ve been keeping busy here at CJUG World Headquarters, so let’s get right to it.

=== Java News

link:http://www.java-countdown.xyz/[The countdown to the Java 11 release] on September 25th has started. This will be the Long Term Support version, meaning it will get security and stability patches for three years. If you’ve been reluctant to upgrade to Java 9 or 10, consider checking out 11, it will be around for a while, even after 12 comes out. Major features of Java 11 are an official HTTP client, some bytecode changes to make future features possible, local variable syntax for lambda parameters, as well as moving Java EE and CORBA packages out of the standard distribution. Give it a try, let us know what you think!

Speaking of Java 11, are you having trouble figuring out what Long Term Support really means, and what the latest news on free vs. paid support is? You aren’t alone. Stephen Colebourne, the person who brought us Joda Time as well as the JSR-310 spec lead has link:https://blog.joda.org/2018/08/java-is-still-available-at-zero-cost.html[a great blog post explaining your options].

=== Polyglot Mixer 

It’s back! Let’s get together with developers from CJUG, Chicago Python (ChiPy), and Chicago Ruby and have some fun! This event is totally free and will be held on Tuesday, September 27, at link:https://www.google.com/maps/place/Sully's+House/@41.908668,-87.649115,15z/data=!4m2!3m1!1s0x0:0xed1b2d4ac822677f?sa=X&ved=2ahUKEwiA-OawwbHdAhUFEywKHe6YB_gQ_BIwEXoECAgQCw[Sully’s House (1501 N. Dayton)]. 

link:http://chicagopolyglot.com/[RSVP for the Polyglot Mixer Now]! 

=== Upcoming Events

*REST Beyond the Obvious - API Design for Ever Evolving Systems* +
Thursday, September 20 at Blue Cross Blue Shield

a.k.a. RESTBTO-ADFEES. Rolls off the tongue. 

link:https://twitter.com/olivergierke[Oliver Gierke] is coming all the way from Dresden, Germany to present this talk and it’s one we think you’ll really learn a lot from. The talk takes a step back and looks at the architectural context APIs live in and outlines the drawbacks that result from ignoring crucial parts of REST. It discusses internal vs. external APIs, whether that distinction is useful in the first place, the impact of Domain-Driven Design and how to design and specify APIs and their clients to optimize for evolvability so that changes in an API don’t break clients.

Oliver was gracious enough to offer the community a choice in what he presented and this was the winner of the vote! So if you voted, thank you! 

link:https://www.meetup.com/ChicagoJUG/events/253582501/[RSVP for Oliver’s talk now]!


*Office Hours* +
Monday. September 17 at IBM

Got a project you need help with? New to Java and want some concepts explained, or help sorting out all of your options? Want to just come hang out and code? Come to CJUG Office Hours. 

Our optional topic this month is going to be Unit Testing, led by Lamar Smith. Learn some of the tools, tricks, and reasons for writing effective unit tests. It might be more effort up front, but it will save you in the long run! Or bring any other questions you might have, projects you want help with, just come hang out.

link:https://www.meetup.com/ChicagoJUG/events/254457791/[RSVP for Office Hours now]!

=== Java Off Heap

Several members of the CJUG board have a podcast focused on Java news called Java Off Heap, and you can find it in link:https://itunes.apple.com/us/podcast/javapubhouse-off-heaps-podcast/id985064111?mt=2[iTunes] or link:http://www.javaoffheap.com/[javaoffheap.com].

link:http://www.javaoffheap.com/2018/09/episode-36-jakarta-ee-elections-make.html[Episode 36]: So another company made the exclusive trillion dollar club (AAPL). We also have Jakarta EE Election Results! (We presume there was no Russian Interference...yet ;). Hear what it means with the new leadership, and who is conspicuously absent from the table. For IDE Buffs, we dived into both Eclipse and Netbeans releases (Eclipse Photon, and Netbeans 9)... so geeks rejoice! Lastly we take a tour on the current Docker Image landscape and what companies are doing for Java in that space.

=== Chirp!
Be sure to follow link:https://twitter.com/cjug[CJUG on twitter @CJUG] for up to date information on what we’re up to. We announce all of our meetups and tweet out interesting news from our industry. As always, be part of the community by tweeting us your suggestions or requests for speakers or topics.

=== Thank You!
We couldn’t do what we do for the Java community in Chicago without the help of our fantastic Gold Level Sponsors. They fund our operations, donate equipment, and generously donate their time and space for us to meet. Please consider them if you are looking to switch jobs soon.

*Expedia Group*

Expedia has generously donated 30 laptops for CJUG which were recently used at our first CJUG4Kids event. We appreciate Expedia’s generous donation to the Chicago Java User Group and we look forward to using the laptops for more events especially CJUG4Kids.  Additionally, Expedia has been very generous with their space for a number of CJUG events.  We are very excited to have them on as Gold Sponsors!

*PEAK6*

PEAK6 has provided CJUG with a generous donation that will help fund additional laptop chargers, speaker gifts, and community events (such as the Polyglot Party!). PEAK6 has been tremendous community partners over the years supplying space, speakers, and frosty beverages. We are very thankful for there support and look forward to partnering with them as Gold Sponsors.
Contact Us

Interested in having your company host a future CJUG meetup? Want to help but don’t know where to start?  Have an idea for a topic that you want to see more of, or want to present yourself? How about some feedback on CJUG to make it better? 

Mail us at link:mailto:board@cjug.org[board@cjug.org] and we will hook you up with the right person.

=== Finally...

We hope to see you at one of our events in September. We’re trying very hard to create an open and inclusive group, so come say “hi!” if you see one of us, and tell your friends and co-workers about what we’re up to.


Thanks for reading,

*Todd Ginsberg* +
*CJUG Community Leader* +
todd.ginsberg@cjug.org


