title=Newsletter March 2017
date=2017-03-20
type=post
tags=blog, asciidoc
status=published
~~~~~~
= Newsletter March 2017
2017-03-20

Hello CJUG-ers!

I hope your year has been shaping up well so far with all the amazing tech events in the city. I’m thrilled, as the new Community Leader for Chicago Java Users Group, to be sending out an update for all the exciting meetups we have planned. Just as a quick retrospective, so far we’ve had great speakers to start off our year, eg. Paul Naumann gave a talk on Building a Better JVM couple of weeks ago, Bob Paulin and Michael Minella talked about Breaking Into Open Source. Hopefully you’ve also had a chance to mingle with the speakers at one of the after-meetup-drinks too!

I also encourage you to take the survey for the topics you’d like to see speakers talk on. You can vote for Johan Andrén to speak on Akka Clustering or Akka Streaming and Alpakka.

We want to get attendees more involved with the community. Feel free to find one of us Board Members at a meetup and we can explore ideas together on how to get you more connected with the community and/or with mentors/mentees. Participating in Office Hours is also a great way to engage with engineers who share your passion for all things Java/JVM! We’re also active in #java, #scala, #kotlin etc. on link:https://chicago-tech.slack.com[chicago-tech.slack.com]

=== Upcoming CJUG Meetups


link:https://www.meetup.com/ChicagoJUG/events/238044574/[CJUG Office Hours - Janine Patterson & Todd Ginsberg (March 21)]

Need help with a project?  Would you like a second pair of eyes to dig into that tricky issue you’ve been facing?  Or do you just want to hang out with your laptop and some people after work?  We’ve got just the thing for you!  Introducing CJUG Office Hours!

Office Hours will be hosted after work.  Every session will have at least one aide in attendance for the full session.  The purpose of these sessions is similar to that of a ‘coffee and code’ - connecting with people who want to work on personal projects, get a code review, or just hang out.  There is no set format and you may come and go as you please.


link:https://www.meetup.com/ChicagoJUG/events/237330626/[Marcus Hirt: Java Mission Control & JFR in JDK 9: A Sneak Peek (March 28)]

In JDK 9, the JFR APIs will become supported, so you can now rely on the JFR APIs for both controlling Oracle Java Flight Recorder and introducing your own custom JFR data into the recordings. Also, with JDK 9, a new major, very different version of the Oracle Java Mission Control feature of Oracle Java SE Advanced will be released.

This session takes a sneak peek into what the new APIs for controlling the Oracle Java Flight Recorder feature will look like and provides migration guidelines from the old APIs. It also goes through some of the highlights of the completely redesigned Oracle Java Mission Control 6.0.0, such as the automatic analysis of flight recordings.


link:https://www.meetup.com/ChicagoJUG/events/238213369/[GOTO NIGHTS with Frank Greco, Jim Weaver and Ed Burns (April 4)]

Introduction to Machine Learning for Java Developers

Machine Learning (ML) is a powerful data analytics tool that essentially allows machines to solve problems without explicit programming. ML is used in search, marketing, adaptive websites, online advertising, stock market analysis, and even inside of IDE's.  Google's CEO, Sundar Pichai, has said his company is betting big on advances in artificial intelligence (AI) and machine learning in the coming years.  Tim Cook from Apple stated "Today, machine learning drives improvement in countless features across our products”.  At Microsoft's Ignite conference, CEO Satya Nadella talked about his vision for how deep learning and AI will transform the company.

But what exactly is ML?  How is it different from the previous AI technology cycle?  What use cases are suitable for ML?  And most importantly, how can we Java developers take advantage of ML in our applications?

We'll take a look at the various ML services and tools available to Java developers.  In particular we'll explore the Watson Java SDK to demonstrate some powerful ML functionality on a mobile device.  Also, we'll discuss the details of an exciting, proposed JSR for visual recognition.


link:https://www.meetup.com/ChicagoJUG/events/237891217/[Heather VanCura and Charlie Hunt Present: Hacking on Java 9 Round 2 (April 11)]

Bring your project and run it on Java 9 EA with fellow CJUG members! See if the performance improvements Charlie and Heather did a hack day for us in April 2016.  Java 9 is targeted for release for July 2017 but that doesn't mean you need to wait until next year to understand how the new features might benefit your projects. Charlie will be there for anything that breaks (no pressure). Also learn how to take part in Java technology evolution through the Java Community Process (JCP) program run by Heather VanCura. You can participate as an individual, corporation, or nonprofit such as a Java user group (JUG). This session gives you step-by-step instructions on how to participate in the JCP Program with the new membership levels. You will also learn about the global Adopt-a-JSR program and how you can participate in the Adopt-a-JSR program through CJUG. Find out how you have contribute to the future editions of the Java Standard and Java Enterprise Editions.

=== Other Events

link:http://event.scaladays.org/scaladays-chicago-2017[Scala Days (Chicago, April 18-21)]

Scala Days, the premier Scala Conference, will be held this year at Swissôtel in Chicago. Trainings will be on April 18th - 19th, 2017, and the conference will be held from April 19th - 21st, 2017. Leaders from Scala User Groups and communities around the globe, students and language contributors, will gather to discuss academic research, use-cases and visionary projects for a two day, action-packed event. *Use ‘Scaladaysfriend’ code for 20% off tix!*


link:https://gotochgo.com/[GoTo Conference (Chicago, May 1-4)]

Your local Chicago Conference. Great presenters, great people, local venue. This should be an easy win for you to convince your boss to sign-up for! *Use code "CJUGgoto" for $120 off.*


Extra-special goto sessions which might be relevant to CJUG:

- link:https://gotochgo.com/2017/sessions/54[Javaloution! (How I learned to stop worrying and play Jenga! with the entire software industry. What could possibly go wrong?”)] with Georges Saab
- link:https://gotochgo.com/2017/sessions/47[keynote Martin Fowler: Software Design in the 21st Century]


With that, see you at the next CJUG!

*_Amrita Chavan_*
