title=Newsletter November 2017
date=2017-11-10
type=post
tags=blog, asciidoc
status=published
~~~~~~
= Newsletter November 2017
2017-11-10

Yes folks, it's November already and with that we are wrapping up another year at CJUG! We have had talks from Kafka Streams, to Machine Learning, to Docker Tips and Tricks (https://vimeo.com/channels/1109817/videos), and we will be ending it with Quantum Computing and Lightning talks! So come attend the last of our Meetups this year, as we slide into link:http://meet.meetup.com/wf/click?upn=pEEcc35imY7Cq0tG1vyTt3miACH3kxpXb8TgLtvZl9cNDVLrtlGHZ5fUx-2FeBx5dV4AHS4H-2Fm2jyudOUJIeG9sg-3D-3D_OGSh7qcBXBPPzK5pKXbBZfKU-2BGoI0CvMVdXN4tGAH5fGFW2hAz1y-2B19iGB0-2Bk-2BbCGsD0Co1hd69NcH-2Fos-2BnrfcxV9YF2nkHp6-2Fp-2FityEqWOA0jXDXBKSkgShNJOWvQ4IqNxQ-2BjtBNWBwinCj2EgEf0NS-2B4sX-2BdO-2FTeRND0dowasaOG4U-2BI-2F70XVHo8YF6y2wii31DipLbnkqvnQvPQbEJOIl7-2Bd5GfmY6IMlNgI6o9g-3D[GoTo's holiday party] event as well.

link:http://meet.meetup.com/wf/click?upn=pEEcc35imY7Cq0tG1vyTt3miACH3kxpXb8TgLtvZl9cNDVLrtlGHZ5fUx-2FeBx5dVIYDHtx1dA4-2FAnZht-2BfUvsw-3D-3D_OGSh7qcBXBPPzK5pKXbBZfKU-2BGoI0CvMVdXN4tGAH5fGFW2hAz1y-2B19iGB0-2Bk-2BbCGsD0Co1hd69NcH-2Fos-2BnrfZkgBlGis2c1tqZ36bzLRZfDNd2a729TH6vIEs3Dn6vLtORswmAm6xEXuonZ-2BaRvR-2FtVNyqb-2FU8PULq9CdYYl-2Farsk3Du6-2FxEDEpfeZ81-2BQmPm5GdFsR4fSB-2BbcEzzhRYCk6Fvatg4ufKzTJg4JdGhw-3D[James Weaver Presents: Quantum Computing Exposed - The Fundamentals (Nov 28th)]

Java has just released its first Quantum Compu...oh wait, that's in the other alternate universe. Well, while we don't have Java frameworks for Quantum computing (I'm sure they are going to come), Jim is going to talk about what it is, and why is so exciting. There is no experience necessary to attend this talk, just a cat's curiosity on wanting to learn (If you're schrodinger cat we're both sorry and not sorry at the same time). Sign up now!

link:http://meet.meetup.com/wf/click?upn=pEEcc35imY7Cq0tG1vyTt3miACH3kxpXb8TgLtvZl9cNDVLrtlGHZ5fUx-2FeBx5dVRwmHERUicZuBfgA5TZoGTw-3D-3D_OGSh7qcBXBPPzK5pKXbBZfKU-2BGoI0CvMVdXN4tGAH5fGFW2hAz1y-2B19iGB0-2Bk-2BbCGsD0Co1hd69NcH-2Fos-2BnrfYAnhjQDJ7W4dvQc5ul-2FkK1yYea0D8v-2BSVqFfYAGhGr6chWFM6dzQ6IvA4KYI37DpaZMgaEKB4axgKmY93t50Ih26-2FvWn-2FpqnsQPCZS1VhZ-2Frw-2B3-2ByV5F3qKP4yS6bleymegxvphvP6rNJsdbrdyHyc-3D[Lightning Talks! (Dec 12)]

As a end-cap for the year we host Lighning talks, where the presenter...is you!... That's right. If you ever thought about presenting (or if you just want to have some practice) then participate in our lighning talks. The format is 10 ~ 15 mins on a topic of your choice (can be anything), and then you show up and present! It's a safe environment for you to practice and help manage those presentation shivers (we can coach you too!). Here at CJUG we want to grow the next crop of presenters, so we are waiting for you!

mailto:board@cjug.org[Looking for Volunteers!]

The Chicago Java Users Group is run entirely by volunteers. It's the community that makes it possible to have these events and get awesome speakers and do cool events. If you have participated as a attendee in our CJUG you know we strive to bring you great content and a great experience. How about volunteering? We always need more help, and the more help we have, the better our events! Volunteer can be as little or as much time as you can give. There is no real restriction to hop in and help us organize events. Also, volunteering allows you to connect directly to our company network (and sponsors) expanding who you know, and to top it off it looks great in your resume! So with all these upsides, come and help us! Just reach out to a CJUG Board member (or the M.C.) on any of our events and we'll sign you up!

mailto:board@cjug.org[CJUG believes in Inclusion]

We always have, and we always will. Just now we just want it to make it more explicit. At our Meetups, if there’s someone you don’t know, please introduce yourself. Be curious, ask questions, avoid assumptions, and help us continue to grow this community into one of trust, empathy, and friendship. Also, if you have ideas or suggestions on how to be more inclusive (or any other ideas for that matter) send it to board@cjug.org

Funny of the week

link:http://meet.meetup.com/wf/click?upn=pEEcc35imY7Cq0tG1vyTt-2FtSP-2BEPjrlX4VsfFFSI-2BWuNxM7PmPVLjnP34KE0F56XAw0nceppgvpIgJoE7u9FwxQUgxCvF59FlGVXh-2BzeVCY-3D_OGSh7qcBXBPPzK5pKXbBZfKU-2BGoI0CvMVdXN4tGAH5fGFW2hAz1y-2B19iGB0-2Bk-2BbCGsD0Co1hd69NcH-2Fos-2BnrfQ5pMCblSk47laeAjaIkkveMfK7huUtqxvRRik225U89U3IMYSbkDGLuMFdlICuJc4ta9uNmO-2F3Kr-2FqP8Z17iSjvKdJjvS3ZaatfeC63Z9XU0CKU2BnAVgYkPjwcJUT2S0xxss963oXHBoLOTwTNGSQ-3D[Coming from I Am Devloper]

.1969:
* what're you doing with that 2KB of RAM?
* sending people to the moon

.2017:
* what're you doing with that 1.5GB of RAM?
* running Slack

*_Thank you!_*

*_Freddy Guime_*

*_Official Cat Herder for CJUG_*


